// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RouterFinder.Infra.Context;

namespace RouterFinder.Infra.Migrations
{
    [DbContext(typeof(RouterFinderContext))]
    partial class RouterFinderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RouterFinder.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("routeDescription")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("routeFrom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("routeTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("routeValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4639706-7262-4731-81cb-17398bc7f9d6"),
                            routeDescription = "GRU -> BRC",
                            routeFrom = "GRU",
                            routeTo = "BRC",
                            routeValue = 10.0
                        },
                        new
                        {
                            Id = new Guid("c806da72-a078-432b-ac1b-2e85cf711e5e"),
                            routeDescription = "GRU -> CDG",
                            routeFrom = "GRU",
                            routeTo = "CDG",
                            routeValue = 75.0
                        },
                        new
                        {
                            Id = new Guid("fdd84c1e-aada-4eb8-a404-ae46298ff6b6"),
                            routeDescription = "GRU -> SCL",
                            routeFrom = "GRU",
                            routeTo = "SCL",
                            routeValue = 20.0
                        },
                        new
                        {
                            Id = new Guid("8a4e2ceb-7da8-475a-a42a-e14de554e4b3"),
                            routeDescription = "GRU -> ORL",
                            routeFrom = "GRU",
                            routeTo = "ORL",
                            routeValue = 56.0
                        },
                        new
                        {
                            Id = new Guid("78f9678b-3a82-4740-a96a-6d3f84019b45"),
                            routeDescription = "BRC -> SCL",
                            routeFrom = "BRC",
                            routeTo = "SCL",
                            routeValue = 5.0
                        },
                        new
                        {
                            Id = new Guid("b4032e1e-9fbd-4292-93a7-15282df694bd"),
                            routeDescription = "ORL -> CDG",
                            routeFrom = "ORL",
                            routeTo = "CDG",
                            routeValue = 5.0
                        },
                        new
                        {
                            Id = new Guid("42fdc1d8-2389-476a-8390-41ab769bf02d"),
                            routeDescription = "SCL -> ORL",
                            routeFrom = "SCL",
                            routeTo = "ORL",
                            routeValue = 20.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
